baseURL: "https://example.org/"
languageCode: "en-us"
title: "mheck136"
theme: "github.com/adityatelange/hugo-PaperMod"
params:
  homeInfoParams:
    Title: Welcome to my blog!
    Content: >
        # Topics I'm interested in:

        - Go

        - Kubernetes

        - DDD
  socialIcons:
    - name: github
      url: "https://github.com/mheck136"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/story/2371145"
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
